# Generated by Django 4.1.2 on 2022-10-09 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_simulacao', models.DateField()),
                ('cod_rep', models.IntegerField()),
                ('cod_cliente', models.IntegerField()),
                ('cod_empr', models.IntegerField()),
                ('situacao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item', models.CharField(max_length=20)),
                ('cod_mascara', models.CharField(blank=True, max_length=20)),
                ('qtde', models.IntegerField()),
                ('valor', models.FloatField()),
                ('ean_item', models.CharField(max_length=20)),
                ('situacao', models.BooleanField(default=True)),
                ('id_simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdvSimulations.simulacao')),
            ],
        ),
    ]
