# Generated by Django 4.1.2 on 2022-10-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdvSimulations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itens',
            new_name='Itens_Simulacao',
        ),
    ]
