# Generated by Django 4.1.2 on 2022-10-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvSimulations', '0002_rename_itens_itens_simulacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao',
            name='cod_empr',
            field=models.IntegerField(default=1),
        ),
    ]
