# Generated by Django 4.1.2 on 2022-10-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdvSimulations', '0003_alter_simulacao_cod_empr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itens_simulacao',
            old_name='id_simulacao',
            new_name='simulacao',
        ),
    ]
