# Generated by Django 4.1.2 on 2022-10-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvSimulations', '0004_rename_id_simulacao_itens_simulacao_simulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='observacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='tipo_simulacao',
            field=models.IntegerField(choices=[(1, 'Tipo1'), (2, 'Tipo2'), (3, 'Tipo3'), (4, 'Tipo4'), (5, 'Outro')], default=1),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='txt_verba1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='txt_verba2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='txt_verba3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='txt_verba4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='txt_verba5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='vlr_verba1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='vlr_verba2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='vlr_verba3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='vlr_verba4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='vlr_verba5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='itens_simulacao',
            name='ean_item',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
