# Generated by Django 4.1.3 on 2022-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvSimulations', '0006_alter_simulacao_vlr_verba1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='tipo_evento',
            field=models.IntegerField(choices=[(0, 'NENHUM'), (1, 'DESCONTOS ESCALONADOS 2% '), (2, 'DESCONTOS ESCALONADOS 5% GER'), (3, 'DESCONTOS ESCALONADOS 7% GER'), (4, '10/11 - 9,10%'), (5, '12/13 - 7,69%'), (6, '20/01 - 4,80%'), (7, 'BÔNUS 1%'), (8, 'BÔNUS 2%'), (9, 'PRAZO - 2% (30 DIAS)'), (10, 'PRAZO - 4% (60 DIAS)'), (11, 'PRAZO - 6% (90 DIAS)'), (11, 'VERBA VALOR FECHADO)')], default=0),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='tipo_simulacao',
            field=models.IntegerField(choices=[(0, 'NENHUM'), (1, 'MENSAL'), (2, 'TRIMESTRAL'), (3, 'DIA DAS MAES'), (4, 'DIA DOS PAIS'), (5, 'NATAL'), (6, 'BLACK FRIDAY'), (7, 'ANIVERSARIO CLIENTE'), (8, 'BONUS PERFORMACE')], default=0),
        ),
    ]
